[theme]
primaryColor = "#FF1493"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FFFFFF"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
showErrorDetails = true

[logger]
level = "info"

[client]
caching = true
displayEnabled = true
showErrorDetails = true
